**List of tuple**

In [ ]:
!pip install pandas

In [2]:
import pandas as pd

In [14]:
empdata = [(101,'Arya','Pune'),
          (102,'Umesh','Mumbai'),
          (103,'Om','Chennai')]
df = pd.DataFrame(empdata,columns=['id','name','city'])

In [16]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103     Om  Chennai

**List of List**

In [2]:
import pandas as pd

In [3]:
empdata = empdata = [[101,'Arya','Pune'],
          [102,'Umesh','Mumbai'],
          [103,'Om','Chennai']]
df = pd.DataFrame(empdata,columns=['id','name','city'])

In [4]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103     Om  Chennai

**Tuple of List**

In [5]:
import pandas as pd

In [6]:
empdata = empdata = ([101,'Arya','Pune'],
          [102,'Umesh','Mumbai'],
          [103,'Om','Chennai'])
df = pd.DataFrame(empdata,columns=['id','name','city'])

In [7]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103     Om  Chennai

**Tuple of Tuple**

In [8]:
import pandas as pd

In [9]:
empdata = empdata = ((101,'Arya','Pune'),
          (102,'Umesh','Mumbai'),
          (103,'Om','Chennai'))
df = pd.DataFrame(empdata,columns=['id','name','city'])

In [10]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103     Om  Chennai

**List of Dictionary**

In [11]:
import pandas as pd

In [12]:
empdata = empdata = [{'id':101,'name':'Arya','city':'Pune'},
          {'id':102,'name':'Umesh','city':'Mumbai'},
          {'id':103,'name':'Om','city':'Chennai'}]
df = pd.DataFrame(empdata)

In [13]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103     Om  Chennai

**Dictionary with List**

In [14]:
import pandas as pd

In [17]:
empdata = empdata = {'id':[101,102,103],
          'name':['Arya','Umesh','Priya'],
          'city':['Pune','Mumbai','Chennai']}
df = pd.DataFrame(empdata)

In [18]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103  Priya  Chennai

**Dictionary with Tuple**

In [20]:
import pandas as pd

In [21]:
empdata = empdata = {'id':(101,102,103),
          'name':('Arya','Umesh','Priya'),
          'city':('Pune','Mumbai','Chennai')}
df = pd.DataFrame(empdata)

In [22]:
df

    id   name     city
0  101   Arya     Pune
1  102  Umesh   Mumbai
2  103  Priya  Chennai